// AUTO-GENERATED by scratchpad/place.py — image manifest extracted from the PDF.
// Maps each project slug to its cover + captioned gallery (captions verbatim from PDF panels).

export type GalleryImage = { src: string; caption: string; width: number; height: number };
export type ProjectImages = { cover: string; gallery: GalleryImage[] };

export const IDENTITY_IMAGES = {
  "residence": "/identity/residence.png"
} as const;

export const PROJECT_IMAGES: Record<string, ProjectImages> = {
  "kitchen-project": {
    "cover": "/projects/kitchen-project/rendered-view-1.png",
    "gallery": [
      {
        "src": "/projects/kitchen-project/rendered-view-1.png",
        "caption": "Rendered View 1",
        "width": 800,
        "height": 479
      },
      {
        "src": "/projects/kitchen-project/rendered-view-2.png",
        "caption": "Rendered View 2",
        "width": 560,
        "height": 508
      },
      {
        "src": "/projects/kitchen-project/rendered-view-3.png",
        "caption": "Rendered View 3",
        "width": 480,
        "height": 303
      },
      {
        "src": "/projects/kitchen-project/rendered-view-4.png",
        "caption": "Rendered View 4",
        "width": 560,
        "height": 318
      },
      {
        "src": "/projects/kitchen-project/rendered-view-5.png",
        "caption": "Rendered View 5",
        "width": 560,
        "height": 315
      },
      {
        "src": "/projects/kitchen-project/references-style-guide.png",
        "caption": "References & Style Guide",
        "width": 491,
        "height": 562
      },
      {
        "src": "/projects/kitchen-project/materials-finishes.png",
        "caption": "Materials and Finishes Guide",
        "width": 560,
        "height": 139
      },
      {
        "src": "/projects/kitchen-project/sketchup-1.jpg",
        "caption": "3D Modeling (SketchUp)",
        "width": 400,
        "height": 203
      },
      {
        "src": "/projects/kitchen-project/sketchup-2.jpg",
        "caption": "3D Modeling (SketchUp)",
        "width": 400,
        "height": 213
      },
      {
        "src": "/projects/kitchen-project/sketchup-3.jpg",
        "caption": "3D Modeling (SketchUp)",
        "width": 400,
        "height": 203
      },
      {
        "src": "/projects/kitchen-project/client-drawings.png",
        "caption": "Client Provided Drawings",
        "width": 480,
        "height": 278
      },
      {
        "src": "/projects/kitchen-project/layout-plan.png",
        "caption": "Kitchen & Laundry Layout Plan",
        "width": 456,
        "height": 474
      },
      {
        "src": "/projects/kitchen-project/dimensional-plan.png",
        "caption": "Kitchen & Laundry Dimensional Plan",
        "width": 453,
        "height": 469
      },
      {
        "src": "/projects/kitchen-project/kitchen-elevations.png",
        "caption": "Kitchen Elevations",
        "width": 560,
        "height": 437
      },
      {
        "src": "/projects/kitchen-project/laundry-elevations.png",
        "caption": "Laundry Elevations",
        "width": 560,
        "height": 344
      },
      {
        "src": "/projects/kitchen-project/electrical-plan.png",
        "caption": "Kitchen & Laundry Electrical Plan",
        "width": 391,
        "height": 473
      }
    ]
  },
  "master-bedroom-permit-set": {
    "cover": "/projects/master-bedroom-permit-set/supporting-render-1.jpg",
    "gallery": [
      {
        "src": "/projects/master-bedroom-permit-set/supporting-render-1.jpg",
        "caption": "Supporting Render 1",
        "width": 480,
        "height": 270
      },
      {
        "src": "/projects/master-bedroom-permit-set/supporting-render-2.jpg",
        "caption": "Supporting Render 2",
        "width": 480,
        "height": 270
      },
      {
        "src": "/projects/master-bedroom-permit-set/supporting-render-3.jpg",
        "caption": "Supporting Render 3",
        "width": 480,
        "height": 270
      },
      {
        "src": "/projects/master-bedroom-permit-set/existing-1.jpg",
        "caption": "Existing Images",
        "width": 320,
        "height": 214
      },
      {
        "src": "/projects/master-bedroom-permit-set/existing-2.jpg",
        "caption": "Existing Images",
        "width": 320,
        "height": 214
      },
      {
        "src": "/projects/master-bedroom-permit-set/existing-3.jpg",
        "caption": "Existing Images",
        "width": 320,
        "height": 214
      },
      {
        "src": "/projects/master-bedroom-permit-set/client-data-1.png",
        "caption": "Client Data",
        "width": 320,
        "height": 240
      },
      {
        "src": "/projects/master-bedroom-permit-set/client-data-2.png",
        "caption": "Client Data",
        "width": 240,
        "height": 320
      },
      {
        "src": "/projects/master-bedroom-permit-set/site-plan.jpg",
        "caption": "Site Plan",
        "width": 560,
        "height": 386
      },
      {
        "src": "/projects/master-bedroom-permit-set/wall-demo.jpg",
        "caption": "Existing Plan Wall Demo",
        "width": 560,
        "height": 386
      },
      {
        "src": "/projects/master-bedroom-permit-set/proposed-extension.jpg",
        "caption": "Proposed Extension",
        "width": 640,
        "height": 441
      },
      {
        "src": "/projects/master-bedroom-permit-set/proposed-roof-plan.jpg",
        "caption": "Proposed Roof Plan",
        "width": 640,
        "height": 441
      },
      {
        "src": "/projects/master-bedroom-permit-set/elevation-front-rear.jpg",
        "caption": "Elevation Front and Rear",
        "width": 640,
        "height": 441
      },
      {
        "src": "/projects/master-bedroom-permit-set/elevation-right-left.jpg",
        "caption": "Elevation Right and Left",
        "width": 640,
        "height": 441
      }
    ]
  },
  "3d-model-rendering": {
    "cover": "/projects/3d-model-rendering/exterior-render.png",
    "gallery": [
      {
        "src": "/projects/3d-model-rendering/exterior-render.png",
        "caption": "Exterior Render (View 1)",
        "width": 720,
        "height": 405
      },
      {
        "src": "/projects/3d-model-rendering/staircase.jpg",
        "caption": "Staircase",
        "width": 267,
        "height": 400
      },
      {
        "src": "/projects/3d-model-rendering/outdoor-sitting.jpg",
        "caption": "Outdoor Sitting",
        "width": 480,
        "height": 435
      },
      {
        "src": "/projects/3d-model-rendering/living-room.jpg",
        "caption": "Living Room",
        "width": 480,
        "height": 320
      },
      {
        "src": "/projects/3d-model-rendering/kitchen.png",
        "caption": "Kitchen",
        "width": 480,
        "height": 320
      },
      {
        "src": "/projects/3d-model-rendering/stair-lobby.jpg",
        "caption": "Stair Lobby",
        "width": 400,
        "height": 400
      },
      {
        "src": "/projects/3d-model-rendering/pool-area.jpg",
        "caption": "Pool Area",
        "width": 267,
        "height": 400
      },
      {
        "src": "/projects/3d-model-rendering/wet-bar.jpg",
        "caption": "Wet Bar",
        "width": 400,
        "height": 325
      },
      {
        "src": "/projects/3d-model-rendering/visualization-process.png",
        "caption": "Visualization Process",
        "width": 553,
        "height": 169
      },
      {
        "src": "/projects/3d-model-rendering/material-palette.png",
        "caption": "Material Palette",
        "width": 640,
        "height": 159
      }
    ]
  },
  "garage-permit-set": {
    "cover": "/projects/garage-permit-set/cover-page.png",
    "gallery": [
      {
        "src": "/projects/garage-permit-set/cover-page.png",
        "caption": "Cover Page",
        "width": 720,
        "height": 296
      },
      {
        "src": "/projects/garage-permit-set/references.jpg",
        "caption": "References by Client",
        "width": 320,
        "height": 241
      },
      {
        "src": "/projects/garage-permit-set/interior-viz-1.jpg",
        "caption": "Interior Visualization",
        "width": 480,
        "height": 227
      },
      {
        "src": "/projects/garage-permit-set/interior-viz-2.jpg",
        "caption": "Interior Visualization",
        "width": 480,
        "height": 227
      },
      {
        "src": "/projects/garage-permit-set/interior-viz-3.jpg",
        "caption": "Interior Visualization",
        "width": 480,
        "height": 227
      },
      {
        "src": "/projects/garage-permit-set/ground-floor-plan.png",
        "caption": "Ground Floor Plan",
        "width": 335,
        "height": 400
      },
      {
        "src": "/projects/garage-permit-set/detailed-floor-plan.png",
        "caption": "Detailed Floor Plan",
        "width": 357,
        "height": 400
      },
      {
        "src": "/projects/garage-permit-set/mezzanine-plan.png",
        "caption": "Mezzanine Floor Plan",
        "width": 369,
        "height": 480
      },
      {
        "src": "/projects/garage-permit-set/roof-plan.png",
        "caption": "Roof Plan",
        "width": 441,
        "height": 480
      },
      {
        "src": "/projects/garage-permit-set/truss-plan.png",
        "caption": "Truss Plan",
        "width": 461,
        "height": 480
      },
      {
        "src": "/projects/garage-permit-set/south-elevation.png",
        "caption": "South Elevation",
        "width": 480,
        "height": 259
      },
      {
        "src": "/projects/garage-permit-set/east-elevation.png",
        "caption": "East Elevation",
        "width": 480,
        "height": 231
      },
      {
        "src": "/projects/garage-permit-set/north-elevation.png",
        "caption": "North Elevation",
        "width": 480,
        "height": 282
      },
      {
        "src": "/projects/garage-permit-set/west-elevation.png",
        "caption": "West Elevation",
        "width": 480,
        "height": 228
      },
      {
        "src": "/projects/garage-permit-set/section-aa.png",
        "caption": "Section AA'",
        "width": 400,
        "height": 277
      },
      {
        "src": "/projects/garage-permit-set/section-bb.png",
        "caption": "Section BB'",
        "width": 480,
        "height": 313
      },
      {
        "src": "/projects/garage-permit-set/cross-section.png",
        "caption": "Cross-Section",
        "width": 293,
        "height": 150
      }
    ]
  },
  "residential-3d-modeling": {
    "cover": "/projects/residential-3d-modeling/exterior-hero.png",
    "gallery": [
      {
        "src": "/projects/residential-3d-modeling/exterior-hero.png",
        "caption": "Exterior Render (View 1)",
        "width": 786,
        "height": 800
      },
      {
        "src": "/projects/residential-3d-modeling/exterior-render-2.jpg",
        "caption": "Exterior Render (View 2)",
        "width": 640,
        "height": 360
      },
      {
        "src": "/projects/residential-3d-modeling/floor-plans.png",
        "caption": "Floor Plans",
        "width": 269,
        "height": 268
      },
      {
        "src": "/projects/residential-3d-modeling/elevations-1.png",
        "caption": "Elevations",
        "width": 359,
        "height": 303
      },
      {
        "src": "/projects/residential-3d-modeling/elevations-2.png",
        "caption": "Elevations",
        "width": 315,
        "height": 243
      },
      {
        "src": "/projects/residential-3d-modeling/sketchup-1.jpg",
        "caption": "SketchUp Screenshots",
        "width": 480,
        "height": 264
      },
      {
        "src": "/projects/residential-3d-modeling/sketchup-2.jpg",
        "caption": "SketchUp Screenshots",
        "width": 480,
        "height": 270
      }
    ]
  },
  "bathroom-project": {
    "cover": "/projects/bathroom-project/rendered-view-1.jpg",
    "gallery": [
      {
        "src": "/projects/bathroom-project/rendered-view-1.jpg",
        "caption": "Rendered View 1",
        "width": 560,
        "height": 315
      },
      {
        "src": "/projects/bathroom-project/modeling-1.jpg",
        "caption": "Modeling Screenshots",
        "width": 400,
        "height": 225
      },
      {
        "src": "/projects/bathroom-project/modeling-2.jpg",
        "caption": "Modeling Screenshots",
        "width": 400,
        "height": 225
      },
      {
        "src": "/projects/bathroom-project/floor-plan.png",
        "caption": "Bathroom Floor Plan",
        "width": 640,
        "height": 433
      },
      {
        "src": "/projects/bathroom-project/elevation-a.png",
        "caption": "Elevation A",
        "width": 720,
        "height": 366
      },
      {
        "src": "/projects/bathroom-project/elevation-b.png",
        "caption": "Elevation B",
        "width": 720,
        "height": 360
      },
      {
        "src": "/projects/bathroom-project/references.png",
        "caption": "References for Modeling",
        "width": 266,
        "height": 311
      },
      {
        "src": "/projects/bathroom-project/sketch.png",
        "caption": "Client Data & Hand Drawn Sketches",
        "width": 320,
        "height": 269
      },
      {
        "src": "/projects/bathroom-project/communication.png",
        "caption": "Communication Process During Revisions",
        "width": 480,
        "height": 246
      }
    ]
  },
  "clinic-interior": {
    "cover": "/projects/clinic-interior/reception-render.png",
    "gallery": [
      {
        "src": "/projects/clinic-interior/reception-render.png",
        "caption": "Reception Render",
        "width": 560,
        "height": 315
      },
      {
        "src": "/projects/clinic-interior/lobby-render.png",
        "caption": "Lobby Render",
        "width": 720,
        "height": 405
      },
      {
        "src": "/projects/clinic-interior/interior-render-1.png",
        "caption": "Interior Render",
        "width": 320,
        "height": 256
      },
      {
        "src": "/projects/clinic-interior/interior-render-2.png",
        "caption": "Interior Render",
        "width": 320,
        "height": 240
      },
      {
        "src": "/projects/clinic-interior/interior-render-3.png",
        "caption": "Interior Render",
        "width": 320,
        "height": 240
      },
      {
        "src": "/projects/clinic-interior/interior-render-4.png",
        "caption": "Interior Render",
        "width": 320,
        "height": 240
      },
      {
        "src": "/projects/clinic-interior/floorplan.jpg",
        "caption": "Floorplan",
        "width": 257,
        "height": 400
      },
      {
        "src": "/projects/clinic-interior/furniture-board.jpg",
        "caption": "Furniture and Material Board",
        "width": 400,
        "height": 243
      },
      {
        "src": "/projects/clinic-interior/material-board.jpg",
        "caption": "Furniture and Material Board",
        "width": 560,
        "height": 394
      }
    ]
  },
  "bathroom-documentation": {
    "cover": "/projects/bathroom-documentation/rendered-view-1.png",
    "gallery": [
      {
        "src": "/projects/bathroom-documentation/rendered-view-1.png",
        "caption": "Rendered View 1",
        "width": 560,
        "height": 420
      },
      {
        "src": "/projects/bathroom-documentation/communication.png",
        "caption": "Communication Process During Revisions",
        "width": 720,
        "height": 417
      },
      {
        "src": "/projects/bathroom-documentation/sketch.png",
        "caption": "Client Data & Hand Drawn Sketches",
        "width": 439,
        "height": 249
      },
      {
        "src": "/projects/bathroom-documentation/floor-plan.png",
        "caption": "Bathroom Floor Plan",
        "width": 400,
        "height": 271
      },
      {
        "src": "/projects/bathroom-documentation/tiles-details.png",
        "caption": "Bathroom Tiles Details",
        "width": 320,
        "height": 218
      },
      {
        "src": "/projects/bathroom-documentation/elevation-a.png",
        "caption": "Elevation A",
        "width": 337,
        "height": 323
      },
      {
        "src": "/projects/bathroom-documentation/elevation-b.png",
        "caption": "Elevation B",
        "width": 295,
        "height": 344
      },
      {
        "src": "/projects/bathroom-documentation/elevation-c.png",
        "caption": "Elevation C",
        "width": 400,
        "height": 301
      },
      {
        "src": "/projects/bathroom-documentation/elevation-d.png",
        "caption": "Elevation D",
        "width": 306,
        "height": 320
      },
      {
        "src": "/projects/bathroom-documentation/elevation-e.png",
        "caption": "Elevation E",
        "width": 292,
        "height": 320
      },
      {
        "src": "/projects/bathroom-documentation/elevation-f.png",
        "caption": "Elevation F",
        "width": 400,
        "height": 322
      },
      {
        "src": "/projects/bathroom-documentation/modeling-1.jpg",
        "caption": "Modeling Screenshots",
        "width": 640,
        "height": 340
      },
      {
        "src": "/projects/bathroom-documentation/modeling-2.jpg",
        "caption": "Modeling Screenshots",
        "width": 400,
        "height": 213
      }
    ]
  },
  "3d-modeling": {
    "cover": "/projects/3d-modeling/final-render-1.jpg",
    "gallery": [
      {
        "src": "/projects/3d-modeling/final-render-1.jpg",
        "caption": "Final Renders",
        "width": 560,
        "height": 315
      },
      {
        "src": "/projects/3d-modeling/final-render-2.jpg",
        "caption": "Final Renders",
        "width": 560,
        "height": 315
      },
      {
        "src": "/projects/3d-modeling/final-render-3.jpg",
        "caption": "Final Renders",
        "width": 560,
        "height": 315
      },
      {
        "src": "/projects/3d-modeling/client-drawings-1.png",
        "caption": "Client Provided Drawings",
        "width": 560,
        "height": 291
      },
      {
        "src": "/projects/3d-modeling/client-drawings-2.png",
        "caption": "Client Provided Elevations",
        "width": 560,
        "height": 290
      },
      {
        "src": "/projects/3d-modeling/screenshot-1.jpg",
        "caption": "Screenshot 1",
        "width": 560,
        "height": 285
      },
      {
        "src": "/projects/3d-modeling/screenshot-2.jpg",
        "caption": "Screenshot 2",
        "width": 480,
        "height": 262
      },
      {
        "src": "/projects/3d-modeling/screenshot-3.jpg",
        "caption": "Screenshot 3",
        "width": 480,
        "height": 255
      }
    ]
  },
  "modern-bathroom": {
    "cover": "/projects/modern-bathroom/render-view-1.png",
    "gallery": [
      {
        "src": "/projects/modern-bathroom/render-view-1.png",
        "caption": "Render View 1",
        "width": 480,
        "height": 373
      },
      {
        "src": "/projects/modern-bathroom/render-view-2.png",
        "caption": "Render View 2",
        "width": 560,
        "height": 436
      },
      {
        "src": "/projects/modern-bathroom/working-drawings.png",
        "caption": "Working Drawings & Elevations",
        "width": 560,
        "height": 437
      },
      {
        "src": "/projects/modern-bathroom/layout-options.png",
        "caption": "Layout Options",
        "width": 326,
        "height": 464
      },
      {
        "src": "/projects/modern-bathroom/inspiration-1.png",
        "caption": "Inspiration Photos",
        "width": 446,
        "height": 407
      },
      {
        "src": "/projects/modern-bathroom/inspiration-2.png",
        "caption": "Inspiration Photos",
        "width": 270,
        "height": 341
      },
      {
        "src": "/projects/modern-bathroom/client-data-1.jpg",
        "caption": "Client Data",
        "width": 320,
        "height": 240
      },
      {
        "src": "/projects/modern-bathroom/client-data-2.jpg",
        "caption": "Client Data",
        "width": 240,
        "height": 320
      }
    ]
  },
  "2d-layout-plan": {
    "cover": "/projects/2d-layout-plan/final-furniture-layout.jpg",
    "gallery": [
      {
        "src": "/projects/2d-layout-plan/final-furniture-layout.jpg",
        "caption": "Final Furniture Layout",
        "width": 800,
        "height": 762
      },
      {
        "src": "/projects/2d-layout-plan/client-data-1.jpg",
        "caption": "Client Data",
        "width": 420,
        "height": 560
      },
      {
        "src": "/projects/2d-layout-plan/client-data-2.png",
        "caption": "Client Data",
        "width": 480,
        "height": 443
      }
    ]
  },
  "bedroom-2d-details": {
    "cover": "/projects/bedroom-2d-details/dressing-wall-elevation.png",
    "gallery": [
      {
        "src": "/projects/bedroom-2d-details/dressing-wall-elevation.png",
        "caption": "Bedroom Dressing Wall Elevation",
        "width": 720,
        "height": 456
      },
      {
        "src": "/projects/bedroom-2d-details/dressing-wall-details.png",
        "caption": "Bedroom Dressing Wall Details",
        "width": 640,
        "height": 156
      },
      {
        "src": "/projects/bedroom-2d-details/media-wall-elevation.png",
        "caption": "Bedroom Media Wall Elevation",
        "width": 640,
        "height": 470
      },
      {
        "src": "/projects/bedroom-2d-details/media-wall-details.png",
        "caption": "Bedroom Media Wall Details",
        "width": 640,
        "height": 230
      },
      {
        "src": "/projects/bedroom-2d-details/console-details-1.png",
        "caption": "Console Details",
        "width": 446,
        "height": 173
      },
      {
        "src": "/projects/bedroom-2d-details/console-details-2.png",
        "caption": "Console Details",
        "width": 485,
        "height": 177
      }
    ]
  },
  "kitchen-details": {
    "cover": "/projects/kitchen-details/layout-plan.png",
    "gallery": [
      {
        "src": "/projects/kitchen-details/layout-plan.png",
        "caption": "Kitchen Layout Plan",
        "width": 553,
        "height": 560
      },
      {
        "src": "/projects/kitchen-details/dimensional-plan.png",
        "caption": "Kitchen Dimensional Plan",
        "width": 480,
        "height": 456
      },
      {
        "src": "/projects/kitchen-details/elevation-a.png",
        "caption": "Elevation A",
        "width": 153,
        "height": 294
      },
      {
        "src": "/projects/kitchen-details/elevation-b.png",
        "caption": "Elevation B",
        "width": 311,
        "height": 171
      },
      {
        "src": "/projects/kitchen-details/elevation-c.png",
        "caption": "Elevation C",
        "width": 560,
        "height": 293
      },
      {
        "src": "/projects/kitchen-details/elevation-d.png",
        "caption": "Elevation D",
        "width": 320,
        "height": 171
      },
      {
        "src": "/projects/kitchen-details/elevation-e.png",
        "caption": "Elevation E",
        "width": 480,
        "height": 294
      },
      {
        "src": "/projects/kitchen-details/elevation-f.png",
        "caption": "Elevation F",
        "width": 368,
        "height": 306
      }
    ]
  },
  "laundry-details": {
    "cover": "/projects/laundry-details/elevation-b.png",
    "gallery": [
      {
        "src": "/projects/laundry-details/elevation-b.png",
        "caption": "Elevation B",
        "width": 479,
        "height": 388
      },
      {
        "src": "/projects/laundry-details/elevation-a.png",
        "caption": "Elevation A",
        "width": 640,
        "height": 346
      },
      {
        "src": "/projects/laundry-details/layout-plan.png",
        "caption": "Laundry Layout Plan",
        "width": 560,
        "height": 285
      },
      {
        "src": "/projects/laundry-details/dimensional-plan.png",
        "caption": "Laundry Dimensional Plan",
        "width": 560,
        "height": 329
      },
      {
        "src": "/projects/laundry-details/tile-layout.png",
        "caption": "Laundry Tile Layout",
        "width": 560,
        "height": 287
      },
      {
        "src": "/projects/laundry-details/lighting-plan.png",
        "caption": "Laundry Lighting Plan",
        "width": 480,
        "height": 290
      }
    ]
  }
};
